In [3]:
import tensorflow as tf

In [7]:
tf.__version__

'2.3.0'

$ y = w1*x^2+w2*x+b $

$ \frac{dy}{dx}=w1*2*x+w2$

In [9]:
w1 = tf.constant(1.)
w2 = tf.constant(2.)
b = tf.constant(3.)
x = tf.constant(4.)

In [15]:
w1,w2,b,x

(<tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.0>)

with tf.GradientTape() as tape:
    tape.watch(x)
    y = w1*(x**2)+w2*x+b 

dy_dx =tape.gradient(y,x)

dy_dx

y =w*x+b

In [30]:
w = tf.constant(1.)
b = tf.constant(3.)
x = tf.constant(4.)

with tf.GradientTape() as tape:
    tape.watch([w,b])
    y = w*x+b 

In [32]:
[dy_dw,dy_db] = tape.gradient(y,[w,b])

In [33]:
dy_dw,dy_db

(<tf.Tensor: shape=(), dtype=float32, numpy=4.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

$y = \frac{1}{1+e^{-x}}$

In [42]:
x = tf.constant(4.)

In [44]:
with tf.GradientTape() as tape:
    tape.watch(x)
    y = 1/(1+tf.exp(-x))

In [45]:
dy_dx = tape.gradient(y,x)

In [46]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=0.017662706>